services:
  backend:
    build: ./backend
    ports:
      - 4000:4000
    volumes:
      - ./backend:/app:cached
      - /app/node_modules
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - 5050:5050
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
